add alpha to palette
LiveTyping/android-colors pull request #1
Opened 2017-05-03 13:25 UTC by ogogorev

2017-05-03 14:42 UTC, hazolsky requested changes
Поставь пожалуйста eslint и исправь места которые он подсветит

2017-05-03 15:03 UTC, jastkand commented on src/components/PaletteTile.js
> +function prepareColorForStyles(colorCode, alpha) { //FIXME Rename?
Лучше так `convertToRGBAColor`

2017-05-03 19:05 UTC, hazolsky commented on src/components/PaletteTile.js
> +    const { name, colorCode, alpha } = this.props;
```const { color, alpha } = this.state;```

2017-05-03 19:23 UTC, hazolsky commented on src/components/PaletteTile.js
> +    const { name, colorCode, alpha } = this.props;
```js
const { color, alpha } = this.state;
```

2017-05-03 19:23 UTC, hazolsky commented on src/lib/getMuiTheme.js
> +      color: palette.PRIMARY.color,
```js
const { PRIMARY, INVERSED_PRIMARY_TEXT, ... } = palette;

...
{
  color: PRIMARY.color,
}
```

2017-05-03 19:23 UTC, hazolsky commented on src/reducers/palette.js
> +  DARK_PRIMARY: {color: '#303F9F', alpha: '1'},
`alpha` лучше быть типа `Number`

2017-05-03 19:23 UTC, hazolsky commented on src/components/PaletteTile.js
> +function prepareColorForStyles(colorCode, alpha) { //FIXME Rename?
Напиши плиз коммент к функции в формате [esdoc](https://esdoc.org/manual/usage/tags.html)

2017-05-03 19:23 UTC, hazolsky commented on src/reducers/palette.js
> +  DARK_PRIMARY: {color: '#303F9F', alpha: '1'},
Пробелы до и после скобочек покажет eslint

2017-05-03 19:23 UTC, hazolsky commented on src/components/PaletteTile.js
> +  return 'rgba(' + rgb[0] + ',' + rgb[1] + ',' + rgb[2] + ',' + alpha + ')';
```js
return `rgba(${rgb.join(',')}, ${alpha})`;
```

2017-05-04 07:38 UTC, ogogorev commented on src/components/PaletteTile.js
> +function prepareColorForStyles(colorCode, alpha) { //FIXME Rename?
+

2017-05-04 11:41 UTC, hazolsky commented on src/components/PaletteTile.js
> +function convertToRGBAColor(colorCode, alpha) {
Добавь ко всем функциям описание и, я думаю, можно мержить.

2017-05-07 19:38 UTC, hazolsky approved these changes

2017-05-07 19:38 UTC, merged