[+] close header help block and save his visibility status in localstorage
LiveTyping/android-colors pull request #12
Opened 2017-08-21 10:17 UTC by Muffassa

[Закрывать верхнюю часть шапки по нажатию на крестик](https://trello.com/c/C9TXPXAW/24-%D0%B7%D0%B0%D0%BA%D1%80%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B2%D0%B5%D1%80%D1%85%D0%BD%D1%8E%D1%8E-%D1%87%D0%B0%D1%81%D1%82%D1%8C-%D1%88%D0%B0%D0%BF%D0%BA%D0%B8-%D0%BF%D0%BE-%D0%BD%D0%B0%D0%B6%D0%B0%D1%82%D0%B8%D1%8E-%D0%BD%D0%B0-%D0%BA%D1%80%D0%B5%D1%81%D1%82%D0%B8%D0%BA)

2017-08-22 12:05 UTC, Muffassa commented
@hazolsky посмотри пожалуйста

2017-08-23 08:19 UTC, hazolsky approved these changes

2017-08-23 08:23 UTC, hazolsky requested changes
>
```
/home/travis/build/LiveTyping/android-colors/src/components/HeaderHelp/HeaderHelp.js
  8:3  error  Missing parentheses around multilines JSX  react/jsx-wrap-multilines
```

2017-08-23 09:03 UTC, Muffassa commented
@hazolsky поправил

2017-08-23 20:22 UTC, hazolsky approved these changes

2017-08-23 20:22 UTC, merged