Feature/ac 21
LiveTyping/android-colors pull request #16
Opened 2017-08-23 10:21 UTC by Muffassa

@hazolsky посмотри пожалуйста + Slack отписывал про проблемы с линтером
[Генератор темы Android](https://trello.com/c/fuVqqkz9/21-%D0%B3%D0%B5%D0%BD%D0%B5%D1%80%D0%B0%D1%82%D0%BE%D1%80-%D1%82%D0%B5%D0%BC%D1%8B-android)
![gif](https://media.giphy.com/media/3ohzAGQCfOEPfx4WOI/giphy.gif)

2017-08-24 09:31 UTC, hazolsky commented
Needs rebase

2017-08-24 16:02 UTC, Muffassa commented
@hazolsky review please

2017-08-29 09:32 UTC, hazolsky requested changes

2017-08-29 09:32 UTC, hazolsky commented on src/components/App/App.js
> +    <MuiThemeProvider muiTheme={getMuiTheme(theme)}>
Let's use a standalone theme provider for non-palette components.
e.g. remove `muiTheme={...}` here and keep it in ComponentView.

2017-08-31 06:18 UTC, Muffassa commented
@hazolsky review please

2017-08-31 13:34 UTC, hazolsky approved these changes

2017-08-31 13:34 UTC, merged