add cards component
LiveTyping/android-colors pull request #2
Opened 2017-05-04 10:25 UTC by ogogorev

2017-05-05 06:41 UTC, hazolsky requested changes

2017-05-05 06:41 UTC, hazolsky commented on src/components/CardComponents.js
> +  cardWithMedia: {
Вот эти стили лучше перенести в `css`-файл, чтобы автопрефиксер нужные свойства добавил

2017-05-05 06:41 UTC, hazolsky commented on src/components/CardComponents.js
> +class CardComponents extends Component {
>[eslint] Component should be written as a pure function (react/prefer-stateless-function)

```js
const CardComponents = () => (
  <div>
    <CardWithMedia />
    <CardWithHeader />
    <CardWithIconButtons />
  </div>
);
```

2017-05-05 06:41 UTC, hazolsky commented on src/components/CardComponents.js
> +class CardComponents extends Component {
Лучше переименовать в `CardsView`, если все-таки хочешь оставить это отдельным компонентом.

2017-05-07 09:46 UTC, ogogorev commented on src/components/CardComponents.js
> +class CardComponents extends Component {
Честно говоря, не понимаю, как можно еще сделать, если не оставлять отдельным компонентом.

2017-05-07 09:54 UTC, ogogorev commented on src/components/CardComponents.js
> +  cardWithMedia: {
документации написано, что у всяких `Card`, `CardHeader`, `CardTitle` и прочих нет свойства `className`, поэтому мне непонятно, как мне прикрутить стили к карточкам через свойство `style`.

2017-08-17 13:25 UTC, closed without merging