[+] copy palette link by click on link icon
LiveTyping/android-colors pull request #29
Opened 2017-09-04 04:29 UTC by Muffassa

I m not sure about this [line](https://github.com/LiveTyping/android-colors/compare/feature/copy-link-to-palette-by-clicking-on-link?expand=1#diff-729498c5aa552df999cc9e99e87f961cR41)
. I have to save the url in the store and getting this in middleware or getting this url by `window.location.href` in component is ok?

2017-09-04 09:10 UTC, hazolsky commented
Storing page url in store seems like an overhead to me. However, i would definitely prefer to keep the component be a pure function. We can provide it as a prop from the container.

2017-09-04 09:15 UTC, hazolsky requested changes
See comment above

2017-09-04 10:29 UTC, Muffassa commented
@hazolsky done

2017-09-07 07:13 UTC, hazolsky approved these changes

2017-09-07 07:13 UTC, merged