Do not store modal contents in component's state
LiveTyping/android-colors pull request #30
Opened 2017-09-07 07:45 UTC by hazolsky

2017-09-07 07:51 UTC, hazolsky commented
While doing this seems to be a good idea
https://github.com/LiveTyping/android-colors/blob/05fcbbaeeb7074e2b1b6e3de007ec70b1c541f63/src/components/CopyCodeModal/CopyCodeModal.js#L22-L27
in fact it prevents updating generated android theme when you change colors in palette.

To solve this, we either need to update `state.currentText` each time component receives new props, or not keep that in store at all.

2017-09-07 14:08 UTC, n-filatov requested changes

2017-09-07 14:08 UTC, Muffassa commented on src/components/CopyCodeModal/CopyCodeModal.js
> +          onClick={() => this.onTabChange(tabName)}
Recently read that use arrow functions in render method is bad practise, coz every execution of `render` method creating new instance of this function and it`s bad for performance. And if u want to pass data in calling function u must create component like `Tab` pass this function in props and call it with data( tabName ) from this component. [Link](https://daveceddia.com/avoid-bind-when-passing-props/) on article.

2017-09-08 08:53 UTC, hazolsky commented
@Muffassa good catch 👍 
Does it look better now?

2017-09-08 09:24 UTC, hazolsky commented
Hmm, i was wrong in the implementation above - it won't work. Give me more time to think.

2017-09-08 10:07 UTC, hazolsky commented
There you go @Muffassa

2017-09-08 11:42 UTC, n-filatov approved these changes

2017-09-08 11:43 UTC, merged