Feature/added header image
LiveTyping/android-colors pull request #36
Opened 2017-10-11 13:13 UTC by BloomerWD

@hazolsky Review it, please.

2017-10-12 10:09 UTC, hazolsky commented
Колбасит:
![sreenshot](https://user-images.githubusercontent.com/1270790/31490990-795fd222-af4e-11e7-81d6-09d33e286513.png)
Давай скрывать картинку вообще на узких экранах - она там не нужна.

2017-10-12 10:09 UTC, hazolsky requested changes
Колбасит:
![sreenshot](https://user-images.githubusercontent.com/1270790/31490990-795fd222-af4e-11e7-81d6-09d33e286513.png)
Давай скрывать картинку вообще на узких экранах - она там не нужна.

2017-10-12 10:09 UTC, hazolsky commented on src/components/HeaderHelp/HeaderHelp.js
> +import imgColores from '../../images/colores.png';
Colores -> colors

2017-10-12 10:09 UTC, hazolsky commented on src/components/App/App.css
> +  bottom: -59px;
`-60px`, чтобы прижать картинку к нижнему краю.

2017-10-12 10:45 UTC, BloomerWD commented
@hazolsky Review, please.

2017-10-12 11:13 UTC, hazolsky requested changes
Не обратил на это внимание сразу - давай сделаем кнопку кнопкой, а не div'ом.

2017-10-12 11:32 UTC, BloomerWD commented
@hazolsky Check it, please

2017-10-12 11:38 UTC, hazolsky commented
Needs rebase

2017-10-16 09:30 UTC, hazolsky requested changes
Ломается верстка при нажатии на крестик: https://spacestore.s3.amazonaws.com/s/16_iyh49.mp4

2017-11-27 08:16 UTC, BloomerWD commented
@hazolsky Check, please

2017-11-30 07:04 UTC, hazolsky submitted a review, later dismissed
Looks good, though I'd prefer to not have second, intermediate state of the header — with image at the bottom of the block.
https://spacestore.s3.amazonaws.com/s/30_vfsie.gif
Let's have only 2 states: with image on wide screens and without image on narrow ones.

2017-11-30 07:42 UTC, BloomerWD commented
@hazolsky Check it

2017-11-30 07:57 UTC, hazolsky approved these changes

2017-11-30 07:57 UTC, merged